# Australian's Tyre Trade: Imports, Exports and Trade Balances
## An analysis of trading partners, 2006-2025

The research question: With which trading partners does Australia have a trade deficit, surplus or balance in tyres, treads and tubes, and how have these balances changed over time?

## 1. Data Cleaning

### 1.1 Cleaning Export Data
This section prepares Australia’s export data for rubber tyres, treads and tubes (SITC 625) from 2006 to 2025. 
Then, the number of countries with NaN values is counted, categorised into bins and then dropped from the final clean dataset.

Years will remain as columns, and values will remain in A$ thousands.

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import plotly.express as px
import ipywidgets as widgets
from IPython.display import display, clear_output

In [2]:
export_raw = pd.read_csv("tyre_export.csv", encoding="cp1252", header=None)
export_raw.head(20)

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,AUSTRALIA'S MERCHANDISE EXPORTS AND IMPORTS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Trade type,Total Exports,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Sum of A$000,Column Labels,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Row Labels,2006,2007,2008,2009,2010,2011,2012,2013,2014,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
8,"625 Rubber tyres, treads & tubes",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,...,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,2,NaN
10,Angola,NaN,23,NaN,NaN,6,NaN,16,11,NaN,...,NaN,NaN,21,9,NaN,20,74,5,14,5
11,Antarctica,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,...,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Argentina,"1,283",NaN,NaN,NaN,NaN,NaN,NaN,196,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,107,32
13,Armenia,NaN,NaN,111,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Austria,NaN,NaN,NaN,NaN,NaN,NaN,2,3,NaN,...,7,96,34,NaN,1,NaN,NaN,3,NaN,NaN
15,Azerbaijan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
16,Bahrain,124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,9,NaN
17,Bangladesh,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24,NaN,NaN,NaN,16,NaN,NaN,NaN,NaN,NaN
18,Belgium,474,"1,966","4,848",723,221,417,"1,055","2,711","6,890",...,"9,227","8,274","4,921","4,108",960,84,24,4,3,NaN
19,Belize,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# To check that the total number of items in the dataset matches the CSV
len(export_raw)
# To check how many rows and columns there are
export_raw.shape
# To check which columns contain numbers vs text, and how many missing values there are 
export_raw.info()
# To check for totals or footnotes at the end of the dataset
export_raw.tail()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 177 entries, 0 to 176
Data columns (total 21 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       173 non-null    object
 1   1       92 non-null     object
 2   2       91 non-null     object
 3   3       88 non-null     object
 4   4       76 non-null     object
 5   5       80 non-null     object
 6   6       85 non-null     object
 7   7       83 non-null     object
 8   8       91 non-null     object
 9   9       104 non-null    object
 10  10      92 non-null     object
 11  11      107 non-null    object
 12  12      107 non-null    object
 13  13      100 non-null    object
 14  14      99 non-null     object
 15  15      109 non-null    object
 16  16      94 non-null     object
 17  17      94 non-null     object
 18  18      91 non-null     object
 19  19      85 non-null     object
 20  20      77 non-null     object
dtypes: object(21)
memory usage: 29.2+ KB

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
172,Zambia,45,12,NaN,20,28,13,NaN,NaN,2,...,NaN,251,5,NaN,0,NaN,NaN,NaN,NaN,NaN
173,Zimbabwe,NaN,8,7,17,NaN,23,NaN,NaN,NaN,...,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
174,Türkiye,NaN,64,NaN,NaN,198,NaN,NaN,130,NaN,...,73,NaN,NaN,NaN,NaN,NaN,611,"1,321",916,573
175,Naoero,51,53,78,98,183,343,232,328,302,...,176,131,283,295,303,315,328,438,322,331
176,Grand Total,"66,905","115,575","120,864","52,493","35,718","48,817","62,806","69,007","75,276",...,"102,638","112,586","111,522","105,082","72,551","67,614","134,985","145,901","85,421","75,535"

In [4]:
# To drop the introductory rows from index 0 to 6 and 8
e_clean = export_raw.drop(index=[*range(7),8]).reset_index()
e_clean.head(8)

,index,0,1,2,3,4,5,6,7,8,...,11,12,13,14,15,16,17,18,19,20
0,7,Row Labels,2006,2007,2008,2009,2010,2011,2012,2013,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
1,9,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,2,NaN
2,10,Angola,NaN,23,NaN,NaN,6,NaN,16,11,...,NaN,NaN,21,9,NaN,20,74,5,14,5
3,11,Antarctica,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,...,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,12,Argentina,"1,283",NaN,NaN,NaN,NaN,NaN,NaN,196,...,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,107,32
5,13,Armenia,NaN,NaN,111,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,14,Austria,NaN,NaN,NaN,NaN,NaN,NaN,2,3,...,7,96,34,NaN,1,NaN,NaN,3,NaN,NaN
7,15,Azerbaijan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN

In [5]:
# To change the columns into years and to change the row labels to "Country"

# To drop the old index columns
e_clean = e_clean.drop(columns="index")

# To make the column header be the years
e_clean.columns = e_clean.iloc[0]

# Remove the current year row and reset the row numbers
e_clean = e_clean.iloc[1:].reset_index(drop=True)

# Rename the country column
e_clean = e_clean.rename(columns={"Row Labels": "Country"})

e_clean.head(8)

,Country,2006,2007,2008,2009,2010,2011,2012,2013,2014,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,...,NaN,NaN,NaN,NaN,NaN,6,NaN,NaN,2,NaN
1,Angola,NaN,23,NaN,NaN,6,NaN,16,11,NaN,...,NaN,NaN,21,9,NaN,20,74,5,14,5
2,Antarctica,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,...,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Argentina,"1,283",NaN,NaN,NaN,NaN,NaN,NaN,196,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5,NaN,107,32
4,Armenia,NaN,NaN,111,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Austria,NaN,NaN,NaN,NaN,NaN,NaN,2,3,NaN,...,7,96,34,NaN,1,NaN,NaN,3,NaN,NaN
6,Azerbaijan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN
7,Bahrain,124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,9,NaN

In [6]:
# To check that the total number of items in the dataset matches the CSV
len(e_clean)
# To check how many rows and columns there are
e_clean.shape
# To check which columns contain numbers vs text, and how many missing values there are 
e_clean.info()
# To check for totals or footnotes at the end of the dataset
e_clean.tail()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 21 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  168 non-null    object
 1   2006     89 non-null     object
 2   2007     90 non-null     object
 3   2008     87 non-null     object
 4   2009     75 non-null     object
 5   2010     79 non-null     object
 6   2011     84 non-null     object
 7   2012     82 non-null     object
 8   2013     90 non-null     object
 9   2014     103 non-null    object
 10  2015     91 non-null     object
 11  2016     106 non-null    object
 12  2017     106 non-null    object
 13  2018     99 non-null     object
 14  2019     98 non-null     object
 15  2020     108 non-null    object
 16  2021     93 non-null     object
 17  2022     93 non-null     object
 18  2023     90 non-null     object
 19  2024     84 non-null     object
 20  2025     76 non-null     object
dtypes: object(21)
memory usage: 27.7+ KB

,Country,2006,2007,2008,2009,2010,2011,2012,2013,2014,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
163,Zambia,45,12,NaN,20,28,13,NaN,NaN,2,...,NaN,251,5,NaN,0,NaN,NaN,NaN,NaN,NaN
164,Zimbabwe,NaN,8,7,17,NaN,23,NaN,NaN,NaN,...,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
165,Türkiye,NaN,64,NaN,NaN,198,NaN,NaN,130,NaN,...,73,NaN,NaN,NaN,NaN,NaN,611,"1,321",916,573
166,Naoero,51,53,78,98,183,343,232,328,302,...,176,131,283,295,303,315,328,438,322,331
167,Grand Total,"66,905","115,575","120,864","52,493","35,718","48,817","62,806","69,007","75,276",...,"102,638","112,586","111,522","105,082","72,551","67,614","134,985","145,901","85,421","75,535"

In [7]:
# To pull the Grand Total from the Country dataset
e_total = e_clean[e_clean["Country"]=="Grand Total"].copy()

e_clean = e_clean[e_clean["Country"] != "Grand Total"].copy()

In [8]:
# To confirm that Grand Total is dropped
e_clean.tail()

,Country,2006,2007,2008,2009,2010,2011,2012,2013,2014,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
162,Wallis & Futuna Island,3,27,NaN,NaN,NaN,12,NaN,107,25,...,2,36,6,3,NaN,13,2,NaN,9,10
163,Zambia,45,12,NaN,20,28,13,NaN,NaN,2,...,NaN,251,5,NaN,0,NaN,NaN,NaN,NaN,NaN
164,Zimbabwe,NaN,8,7,17,NaN,23,NaN,NaN,NaN,...,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
165,Türkiye,NaN,64,NaN,NaN,198,NaN,NaN,130,NaN,...,73,NaN,NaN,NaN,NaN,NaN,611,"1,321",916,573
166,Naoero,51,53,78,98,183,343,232,328,302,...,176,131,283,295,303,315,328,438,322,331

In [9]:
# To confirm that Grand Total is saved as e_total
e_total

,Country,2006,2007,2008,2009,2010,2011,2012,2013,2014,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
167,Grand Total,"66,905","115,575","120,864","52,493","35,718","48,817","62,806","69,007","75,276",...,"102,638","112,586","111,522","105,082","72,551","67,614","134,985","145,901","85,421","75,535"

In [10]:
# Confirm the number of countries inside the dataset
e_clean["Country"].nunique()

167

In [11]:
# To select only the year column
year_data = e_clean.drop(columns = "Country")

# Count missing years value per countries
missing_years = year_data.isna().sum(axis=1) # Axis=1: Column / Axis=0: Row

# Group the no. of countries by bins of the number of missing values
missing_bins = pd.cut(missing_years,
                      bins=[-1, 0, 4, 9, 14, 19, 20],
                      labels=["0", "1–4", "5–9", "10–14", "15–19", "20"]
)

# Count countries in each bin, keeping the bin order
missing_bins.value_counts(sort=False)

0        38
1–4      20
5–9      20
10–14    41
15–19    48
20        0
Name: count, dtype: int64

In [12]:
# Keep countries with data for all 20 years
e_comp = e_clean.loc[missing_years == 0].copy()

# Check how many countries remain and were removed
print("Countries Remaining: ", len(e_comp))
print("Countries Removed: ", len(e_clean)-len(e_comp))

# Confirm there are no missing values in the year columns
print(
    "Missing year values",
    e_comp.drop(columns="Country").isna().sum().sum() )
    # The first sum counts missing cells in each year column
    # Adds those column counts into one total

Countries Remaining:  38
Countries Removed:  129
Missing year values 0

In [13]:
# To convert data into int
for year in e_comp.columns[1:]:
    e_comp[year] = (
        e_comp[year]
        .astype(str)
        .str.replace(",","",regex=False)
        .astype(int)
    )
e_comp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 38 entries, 21 to 166
Data columns (total 21 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  38 non-null     object
 1   2006     38 non-null     int64
 2   2007     38 non-null     int64
 3   2008     38 non-null     int64
 4   2009     38 non-null     int64
 5   2010     38 non-null     int64
 6   2011     38 non-null     int64
 7   2012     38 non-null     int64
 8   2013     38 non-null     int64
 9   2014     38 non-null     int64
 10  2015     38 non-null     int64
 11  2016     38 non-null     int64
 12  2017     38 non-null     int64
 13  2018     38 non-null     int64
 14  2019     38 non-null     int64
 15  2020     38 non-null     int64
 16  2021     38 non-null     int64
 17  2022     38 non-null     int64
 18  2023     38 non-null     int64
 19  2024     38 non-null     int64
 20  2025     38 non-null     int64
dtypes: int64(20), object(1)
memory usage: 6.5+ KB

In [14]:
# Keep countries with at least one missing year
e_rem = e_clean.loc[missing_years>0].copy()

# Save the excluded countries and their trade data
e_rem.to_csv("tyre_exports_removed.csv", index=False)

In [15]:
# Save the completed and cleaned export dataset
e_comp.to_csv("tyre_exports_cleaned.csv", index=False)

### 1.2 Cleaning Import Data
This section prepares Australia’s import data for rubber tyres, treads and tubes (SITC 625) from 2006 to 2025. 
Then, the number of countries with NaN values is counted, categorised into bins and then dropped from the final clean dataset.

Years will remain as columns, and values will remain in A$ thousands.

In [16]:
m_raw = pd.read_csv("tyre_import.csv", encoding="cp1252", header=None, dtype=str)
m_raw.head(20)

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,AUSTRALIA'S MERCHANDISE EXPORTS AND IMPORTS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Trade type,Total Imports,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Sum of A$000,Column Labels,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Row Labels,2006,2007,2008,2009,2010,2011,2012,2013,2014,...,2023,2024,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,"625 Rubber tyres, treads & tubes",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Afghanistan,233,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Algeria,NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Anguilla,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
# To check that the total number of items in the dataset matches the CSV
len(m_raw)
# To check how many rows and columns there are
m_raw.shape
# To check which columns contain numbers vs text, and how many missing values there are 
m_raw.info()
# To check for totals or footnotes at the end of the dataset
m_raw.tail()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39514 entries, 0 to 39513
Data columns (total 28 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       140 non-null    object
 1   1       76 non-null     object
 2   2       72 non-null     object
 3   3       69 non-null     object
 4   4       65 non-null     object
 5   5       72 non-null     object
 6   6       74 non-null     object
 7   7       77 non-null     object
 8   8       64 non-null     object
 9   9       69 non-null     object
 10  10      71 non-null     object
 11  11      66 non-null     object
 12  12      71 non-null     object
 13  13      69 non-null     object
 14  14      70 non-null     object
 15  15      66 non-null     object
 16  16      59 non-null     object
 17  17      68 non-null     object
 18  18      66 non-null     object
 19  19      67 non-null     object
 20  20      61 non-null     object
 21  21      0 non-null      object
 22  22      0 non-null      object
 23  23      0 non-null      object
 24  24      0 non-null      object
 25  25      0 non-null      object
 26  26      0 non-null      object
 27  27      0 non-null      object
dtypes: object(28)
memory usage: 8.4+ MB

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
39509,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39510,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39511,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39513,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
# To drop the introductory rows from index 0 to 6 and 8
m_clean = m_raw.drop(index=[*range(14),15]).reset_index()
m_clean.head(8)

,index,0,1,2,3,4,5,6,7,8,...,18,19,20,21,22,23,24,25,26,27
0,14,Row Labels,2006,2007,2008,2009,2010,2011,2012,2013,...,2023,2024,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,16,Afghanistan,233,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,17,Algeria,NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,18,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,19,Anguilla,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,20,Argentina,579,225,17,NaN,118,122,182,572,...,117,58,391,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,21,Armenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,22,Australia,"1,219",922,"1,280",836,822,"1,006","2,421","1,478",...,287,195,74,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
# To change the columns into years and to change the row labels to "Country"

# To drop the old index columns
m_clean = m_clean.drop(columns="index")

# To make the column header be the years
m_clean.columns = m_clean.iloc[0]

# Remove the current year row and reset the row numbers
m_clean = m_clean.iloc[1:].reset_index(drop=True)

# Rename the country column
m_clean = m_clean.rename(columns={"Row Labels": "Country"})

m_clean.head(8)

,Country,2006,2007,2008,2009,2010,2011,2012,2013,2014,...,2023,2024,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Afghanistan,233,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Algeria,NaN,NaN,NaN,5,NaN,NaN,NaN,NaN,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Anguilla,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Argentina,579,225,17,NaN,118,122,182,572,835,...,117,58,391,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Armenia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Australia,"1,219",922,"1,280",836,822,"1,006","2,421","1,478","5,453",...,287,195,74,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Austria,"1,538","3,298",263,4,3,4,5,3,25,...,103,183,102,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
# To check that the total number of items in the dataset matches the CSV
len(m_clean)
# To check how many rows and columns there are
m_clean.shape
# To check which columns contain numbers vs text, and how many missing values there are 
m_clean.info()
# To check for totals or footnotes at the end of the dataset
m_clean.tail()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39498 entries, 0 to 39497
Data columns (total 28 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  135 non-null    object
 1   2006     73 non-null     object
 2   2007     71 non-null     object
 3   2008     68 non-null     object
 4   2009     64 non-null     object
 5   2010     71 non-null     object
 6   2011     73 non-null     object
 7   2012     76 non-null     object
 8   2013     63 non-null     object
 9   2014     68 non-null     object
 10  2015     70 non-null     object
 11  2016     65 non-null     object
 12  2017     70 non-null     object
 13  2018     68 non-null     object
 14  2019     69 non-null     object
 15  2020     65 non-null     object
 16  2021     58 non-null     object
 17  2022     67 non-null     object
 18  2023     65 non-null     object
 19  2024     66 non-null     object
 20  2025     60 non-null     object
 21  nan      0 non-null      object
 22  nan      0 non-null      object
 23  nan      0 non-null      object
 24  nan      0 non-null      object
 25  nan      0 non-null      object
 26  nan      0 non-null      object
 27  nan      0 non-null      object
dtypes: object(28)
memory usage: 8.4+ MB

,Country,2006,2007,2008,2009,2010,2011,2012,2013,2014,...,2023,2024,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39493,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39494,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39495,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39496,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39497,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
# To pull the Grand Total from the Country dataset
m_total = m_clean[m_clean["Country"]=="Grand Total"].copy()

m_clean = m_clean[m_clean["Country"] != "Grand Total"].copy()

In [22]:
# To confirm that Grand Total is dropped
m_clean.tail()

,Country,2006,2007,2008,2009,2010,2011,2012,2013,2014,...,2023,2024,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39493,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39494,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39495,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39496,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39497,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
# Confirm the number of countries in the dataset
m_clean["Country"].nunique()

134

In [24]:
# To select only the year column
year_data = m_clean.drop(columns = "Country")

# Count missing years value per countries
missing_years = year_data.isna().sum(axis=1) # Axis=1: Column / Axis=0: Row

# Group the no. of countries by bins of the number of missing values
missing_bins = pd.cut(missing_years,
                      bins=[-1, 0, 4, 9, 14, 19, 20],
                      labels=["0", "1–4", "5–9", "10–14", "15–19", "20"]
)

# Count countries in each bin, keeping the bin order
missing_bins.value_counts(sort=False)

0         0
1–4       0
5–9      46
10–14    10
15–19    10
20        2
Name: count, dtype: int64

In [25]:
# Keep countries with data for all 20 years
m_comp = m_clean.loc[missing_years == 0].copy()

# Check how many countries remain and were removed
print("Countries Remaining: ", len(m_comp))
print("Countries Removed: ", len(m_clean)-len(m_comp))

# Confirm there are no missing values in the year columns
print(
    "Missing year values",
    m_comp.drop(columns="Country").isna().sum().sum() )
    # The first sum counts missing cells in each year column
    # Adds those column counts into one total

Countries Remaining:  0
Countries Removed:  39497
Missing year values 0

Initial filtering reported 39,497 removed rows. Inspection showed that the CSV contained thousands of entirely blank rows and seven entirely blank columns. The removed-row count therefore did not represent excluded countries. Entirely empty rows and columns were removed before recalculating missing-year counts and filtering trading partners.

In [26]:
# Removing entirely empty rows and columns
m_clean = m_clean.dropna(axis=0, how="all")
m_clean = m_clean.dropna(axis=1, how="all")

# Check the remaining rows and columns
m_clean.shape

(134, 21)

In [27]:
# Count missing years for each import partner
m_year_data = m_clean.drop(columns="Country")
m_missing_years = m_year_data.isna().sum(axis=1)

# Group parterns by their number of missing years
m_missing_bins = pd.cut(
    m_missing_years,
     bins=[-1, 0, 4, 9, 14, 19, 20],
    labels=["0", "1–4", "5–9", "10–14", "15–19", "20"]
)

# Display the number of partners in each bin
m_missing_bins.value_counts(sort=False)

0        41
1–4      10
5–9       8
10–14    13
15–19    62
20        0
Name: count, dtype: int64

In [28]:
# SPlit partners using the updated missing-year counts
m_comp = m_clean.loc[m_missing_years == 0].copy()
m_rem = m_clean.loc[m_missing_years > 0].copy()

print("Countries remaining:", len(m_comp))
print("Countries removed:", len(m_rem))

Countries remaining: 41
Countries removed: 93

In [29]:
m_clean.tail()

,Country,2006,2007,2008,2009,2010,2011,2012,2013,2014,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
129,Venezuela,638,324,12,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,Vietnam,"1,957","1,264","1,112","1,393","4,536","12,646","14,155","13,349","12,269",...,"15,787","25,837","22,509","23,891","36,617","33,071","53,541","51,836","77,774","68,891"
131,Yemen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
132,Türkiye,"16,955","12,609","13,534","13,484","8,961","16,238","20,406","17,596","11,987",...,"13,649","13,069","8,497","7,186","5,255","2,940","4,546","4,329","4,105","4,453"
133,Naoero,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
m_comp.columns[m_comp.columns.duplicated()]

Index([], dtype='object', name=0)

In [31]:
# To convert data into int
for year in m_comp.columns[1:]:
    m_comp[year]=(
        m_comp[year].
            astype(str).
            str.replace(",","",regex=False).
            astype(int)
    )
m_comp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 41 entries, 6 to 132
Data columns (total 21 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  41 non-null     object
 1   2006     41 non-null     int64
 2   2007     41 non-null     int64
 3   2008     41 non-null     int64
 4   2009     41 non-null     int64
 5   2010     41 non-null     int64
 6   2011     41 non-null     int64
 7   2012     41 non-null     int64
 8   2013     41 non-null     int64
 9   2014     41 non-null     int64
 10  2015     41 non-null     int64
 11  2016     41 non-null     int64
 12  2017     41 non-null     int64
 13  2018     41 non-null     int64
 14  2019     41 non-null     int64
 15  2020     41 non-null     int64
 16  2021     41 non-null     int64
 17  2022     41 non-null     int64
 18  2023     41 non-null     int64
 19  2024     41 non-null     int64
 20  2025     41 non-null     int64
dtypes: int64(20), object(1)
memory usage: 7.0+ KB

In [32]:
# Save the excluded countries and trade data
m_rem.to_csv("tyre_imports_removed.csv",index=False)

In [33]:
# Save the completed and cleaned export dataset
m_comp.to_csv("tyre_imports_cleaned.csv", index=False)

## Merging Export and Import Datasets and Calculating Trade Balance

Match `e_comp` and `m_comp` by `Country` using an inner merge, retaining only partners present in both complete-data tables.

Count the partners excluded from each table during matching. The matched dataset will be used to calculate annual trade balances as exports minus imports, measured in A$ thousands.

In [34]:
# Using inner merge, match countries present in both complete datasets
trade_matched = e_comp.merge(
    m_comp,
    on="Country",
    how="inner",
    suffixes=("_EX", "_IM")
) 
# Check the total number of countries that are present in both datasets
print(len(trade_matched))
trade_matched.head(8)

22

,Country,2006_EX,2007_EX,2008_EX,2009_EX,2010_EX,2011_EX,2012_EX,2013_EX,2014_EX,...,2016_IM,2017_IM,2018_IM,2019_IM,2020_IM,2021_IM,2022_IM,2023_IM,2024_IM,2025_IM
0,Canada,1085,1323,1,109,35,30,636,18,278,...,2062,1865,4091,2998,3152,6494,4732,2294,1554,2306
1,China,168,918,1360,762,234,1412,941,946,726,...,633778,679403,753189,771226,748226,861953,992229,1024238,1140308,1201672
2,France,113,97,160,226,82,137,107,165,308,...,26859,38049,54074,50591,40186,38387,47295,33385,34953,34989
3,Germany,128,1170,353,222,300,391,1094,846,399,...,57966,65164,69285,65277,55674,61481,54580,39921,36227,35908
4,Hong Kong (SAR of China),80,1171,1421,1076,4588,6281,6531,8697,10506,...,1844,2659,3923,2910,2338,3125,305,335,117,384
5,India,28,64,6,35,61,430,67,43,269,...,34683,39642,51952,44326,52266,62150,83295,81100,92333,91832
6,Indonesia,3683,4543,4780,2819,443,666,1305,590,227,...,84791,83437,86136,90983,85699,88260,91146,67266,66592,64134
7,Italy,698,1136,2781,1368,521,411,225,258,392,...,13190,15616,10979,11113,12180,18661,22580,22026,26274,27958

In [35]:
# To rearrange the column to 2006_EX, 2006_IM
column_order = ["Country"]

for year in range(2006,2026):
    column_order.append(f"{year}_EX")
    column_order.append(f"{year}_IM")

trade_matched = trade_matched[column_order]

trade_matched.head(8)

,Country,2006_EX,2006_IM,2007_EX,2007_IM,2008_EX,2008_IM,2009_EX,2009_IM,2010_EX,...,2021_EX,2021_IM,2022_EX,2022_IM,2023_EX,2023_IM,2024_EX,2024_IM,2025_EX,2025_IM
0,Canada,1085,3532,1323,2840,1,4112,109,2921,35,...,99,6494,429,4732,568,2294,53,1554,230,2306
1,China,168,250882,918,295504,1360,338421,762,370262,234,...,1956,861953,25490,992229,25883,1024238,15870,1140308,14950,1201672
2,France,113,30580,97,30861,160,42744,226,40924,82,...,2,38387,3,47295,5,33385,7,34953,25,34989
3,Germany,128,40517,1170,41338,353,47131,222,45625,300,...,68,61481,218,54580,4,39921,149,36227,103,35908
4,Hong Kong (SAR of China),80,1687,1171,2973,1421,1414,1076,1342,4588,...,754,3125,207,305,376,335,35,117,131,384
5,India,28,17372,64,13711,6,14251,35,19773,61,...,124,62150,764,83295,420,81100,42,92333,469,91832
6,Indonesia,3683,18985,4543,26904,4780,37634,2819,54352,443,...,673,88260,574,91146,246,67266,584,66592,490,64134
7,Italy,698,21624,1136,15614,2781,15559,1368,12548,521,...,320,18661,193,22580,434,22026,84,26274,117,27958

In [36]:
# To find the number of countries from import and export datasets that are not matched
ex_unmatched = e_comp.loc[
    ~e_comp["Country"].isin(trade_matched["Country"])
].copy()

im_unmatched = m_comp.loc[
    ~m_comp["Country"].isin(trade_matched["Country"])
].copy()

print("Export countries excluded:", len(ex_unmatched))
print(ex_unmatched["Country"].tolist())

print("Import countries excluded:", len(im_unmatched))
print(im_unmatched["Country"].tolist())

print("Total Numbers of Countries matched:", len(trade_matched))

Export countries excluded: 16
['Chile', 'Christmas Island', 'Fiji', 'French Polynesia', 'Ghana', 'Guinea', 'Kiribati', 'Namibia', 'New Caledonia', 'Papua New Guinea', 'Samoa', 'Solomon Islands', 'Timor-Leste', 'Uruguay', 'Vanuatu', 'Naoero']
Import countries excluded: 19
['Australia', 'Austria', 'Belgium', 'Brazil', 'Czech Republic', 'Finland', 'Hungary', 'Israel', 'Luxembourg', 'Mexico', 'Poland', 'Romania', 'Slovak Republic', 'Slovenia', 'Sri Lanka', 'Switzerland', 'Taiwan', 'Vietnam', 'Türkiye']
Total Numbers of Countries matched: 22

In [37]:
# To calculate the Trade Balance across each Year
for year in range(2006,2026): # Loop across years to calculate the trade
    trade_matched[f"{year}_TB"] = (
        trade_matched[f"{year}_EX"]-trade_matched[f"{year}_IM"]
    )

# To group the columns by years
column_order = ["Country"]

for year in range(2006,2026):
    column_order.append(f"{year}_EX")
    column_order.append(f"{year}_IM")
    column_order.append(f"{year}_TB")
trade_matched = trade_matched[column_order]
trade_matched.head()

,Country,2006_EX,2006_IM,2006_TB,2007_EX,2007_IM,2007_TB,2008_EX,2008_IM,2008_TB,...,2022_TB,2023_EX,2023_IM,2023_TB,2024_EX,2024_IM,2024_TB,2025_EX,2025_IM,2025_TB
0,Canada,1085,3532,-2447,1323,2840,-1517,1,4112,-4111,...,-4303,568,2294,-1726,53,1554,-1501,230,2306,-2076
1,China,168,250882,-250714,918,295504,-294586,1360,338421,-337061,...,-966739,25883,1024238,-998355,15870,1140308,-1124438,14950,1201672,-1186722
2,France,113,30580,-30467,97,30861,-30764,160,42744,-42584,...,-47292,5,33385,-33380,7,34953,-34946,25,34989,-34964
3,Germany,128,40517,-40389,1170,41338,-40168,353,47131,-46778,...,-54362,4,39921,-39917,149,36227,-36078,103,35908,-35805
4,Hong Kong (SAR of China),80,1687,-1607,1171,2973,-1802,1421,1414,7,...,-98,376,335,41,35,117,-82,131,384,-253

## Trade Balance Analysis

Among the 22 matched trading partners, with which partners does Australia have a tyre-trade deficit, surplus or balance, and how have these balances changed over 2006–2025?

First, classify each partner’s 2025 trade balance as a surplus, deficit or balance. Then count the number of surplus, deficit and balanced years for each partner across 2006–2025 to identify persistent patterns.

- **Surplus:** exports exceed imports (`TB > 0`).
- **Deficit:** imports exceed exports (`TB < 0`).
- **Balance:** recorded exports equal imports (`TB = 0`).

All trade values are measured in A$ thousands. Findings cover only the 22 partners with complete data, not all Australian tyre trade.

### To find 2025 Trade Balance

In [38]:
# To find the 2025 trade balance and classify the trade balance
bal_2025 = trade_matched[["Country","2025_TB"]].copy()

bal_2025.loc[bal_2025["2025_TB"] > 0, "Status"] = "Surplus"
bal_2025.loc[bal_2025["2025_TB"] < 0, "Status"] = "Deficit"
bal_2025.loc[bal_2025["2025_TB"] == 0, "Status"] = "Balanced"

# Show largest deficit first and largest surpluses last
bal_2025 = bal_2025.sort_values("2025_TB").reset_index().drop(columns="index")
bal_2025

0                    Country  2025_TB   Status
0                      China -1186722  Deficit
1                      Japan  -986340  Deficit
2              United States  -612046  Deficit
3                   Thailand  -484188  Deficit
4                      Spain  -155378  Deficit
5          Republic of Korea   -97293  Deficit
6                      India   -91363  Deficit
7                  Indonesia   -63644  Deficit
8                   Malaysia   -39922  Deficit
9                    Germany   -35805  Deficit
10                    France   -34964  Deficit
11                     Italy   -27841  Deficit
12               Philippines   -14938  Deficit
13                  Portugal   -12128  Deficit
14               Netherlands    -9404  Deficit
15            United Kingdom    -8698  Deficit
16              South Africa    -7359  Deficit
17                 Singapore    -3420  Deficit
18                    Canada    -2076  Deficit
19  Hong Kong (SAR of China)     -253  Deficit
20      United Arab Emirates     1913  Surplus
21               New Zealand    21065  Surplus

#### Observations: 2025 Trade Balances

- Australia recorded tyre-trade deficits with **20 of the 22** matched partners. Only **New Zealand and the United Arab Emirates** recorded surpluses.

- China had the largest deficit at approximately *AUD 1.187 billion*, followed by **Japan** at *AUD 986.340 million* and **the United States** at *AUD 612.046 million*.

- **New Zealand** had the largest surplus at *AUD 21.065 million*, compared with *AUD 1.913 million* for the **United Arab Emirates**.

- **Hong Kong** had the smallest deficit at *AUD 253,000*. No partner had an exactly balanced trade position.

These findings cover only the 22 partners with complete data, not all Australian tyre trade.

### To count how many years each country had a surplus, deficit or balance across 2006-2025

In [39]:
# Select 20 trade-balance columns
tb_columns = [f"{year}_TB" for year in range(2006,2026)]
bal = trade_matched[tb_columns]

# Count each outcome for every country
bal_counts = trade_matched[["Country"]].copy()

bal_counts["Surplus_years"] = (bal > 0).sum(axis=1)
bal_counts["Deficit_years"] = (bal < 0).sum(axis=1)
bal_counts["Balanced_years"] = (bal == 0).sum(axis=1)

# Show countries with the most surplus years first
bal_counts = bal_counts.sort_values(by="Surplus_years", ascending=False).reset_index().drop(columns="index")

bal_counts

0                    Country  Surplus_years  Deficit_years  Balanced_years
0                New Zealand             19              1               0
1   Hong Kong (SAR of China)              9             11               0
2               South Africa              9             11               0
3       United Arab Emirates              9             11               0
4                  Singapore              7             13               0
5                Netherlands              5             15               0
6                      India              0             20               0
7                    Germany              0             20               0
8                     France              0             20               0
9                      China              0             20               0
10                    Canada              0             20               0
11                  Malaysia              0             20               0
12                 Indonesia              0             20               0
13                     Italy              0             20               0
14                  Portugal              0             20               0
15               Philippines              0             20               0
16                     Japan              0             20               0
17         Republic of Korea              0             20               0
18                     Spain              0             20               0
19                  Thailand              0             20               0
20            United Kingdom              0             20               0
21             United States              0             20               0

#### Observations: Trade Balance Patterns, 2006–2025

- **Australia** recorded tyre-trade deficits with *16 of the 22* matched partners in every year from *2006 to 2025*.

- **New Zealand** was the only partner with more surplus years than deficit years, recording 19 surplus years and one deficit year.

- **Hong Kong**, **South Africa** and **the United Arab Emirates** each recorded nine surplus years and 11 deficit years. **Singapore** recorded seven surplus years, while the **Netherlands** recorded five.

- No partner recorded an exactly balanced trade position in any year.

These counts describe how frequently surpluses and deficits occurred, not their monetary size or when changes occurred. Findings apply only to the 22 partners with complete data.

## Interactive Chart: Australia’s Tyre Trade Balances by Partner, 2006–2025

In [40]:
# Turn the yearly trade-balance columns into rows
trade_long = trade_matched.melt(
    id_vars="Country",
    value_vars=tb_columns,
    var_name="Year",
    value_name="Trade_balance"
)

# Convert labels such as "2006_TB" into integer 2006
trade_long["Year"] = (
    trade_long["Year"].str.replace("_TB","",regex=False).astype(int)
)

trade_long.head()

                    Country  Year  Trade_balance
0                    Canada  2006          -2447
1                     China  2006        -250714
2                    France  2006         -30467
3                   Germany  2006         -40389
4  Hong Kong (SAR of China)  2006          -1607

In [41]:
# To plot for each country: plot trade balance on year
fig = px.line(
    trade_long.sort_values("Year"),
    x="Year",
    y="Trade_balance",
    color="Country",
    title="Australia’s Tyre Trade Balances by Partner, 2006–2025",
    labels={"Trade_balance": "Trade balance (A$ thousands)"}
)

# Add a reference line separating surplus and deficit
fig.add_hline(y=0, line_dash="dash", line_color="grey")

fig.show()

### Observations: Trade Balances Over Time

Australia’s tyre-trade deficits with China, Japan and the United States widened overall between 2006 and 2025, although their balances fluctuated during the period.

China’s deficit grew substantially, reaching approximately AUD 1.187 billion in 2025.

Many other partners appear close to zero because their trade balances are much smaller in magnitude. This does not mean their balances remained constant; viewing selected countries separately makes their changes easier to see.

These findings describe the 22 matched partners and do not establish the causes of the changes.

In [42]:
# To make the graph more interactive, allow the user to enter a country name and the graph display that particular country's chart
# Creates 3 interface components: A text box, A button and an output area
country_input = widgets.Text(
    value="Canada",
    placeholder="Canada, Japan, New Zealand",
    description="Countries:",
    layout=widgets.Layout(width="600px")
)
plot_button = widgets.Button(description="Plot")
chart_output = widgets.Output()

In [43]:
def update_chart(button):
    # Read the country names entered in the box
    countries = [
        name.strip()
        for name in country_input.value.split(",")
        if name.strip()
    ]

    with chart_output:
        clear_output(wait=True)

        # Check the names
        available = trade_long["Country"].unique()
        unknown = [name for name in countries if name not in available]

        if not countries:
            print("Enter at least one country.")
            return

        if unknown:
            print("Country names not found:", ", ".join(unknown))
            return

        # Select those countries and plot their balances
        selected = trade_long[
            trade_long["Country"].isin(countries)
        ].sort_values("Year")

        fig = px.line(
            selected,
            x="Year",
            y="Trade_balance",
            color="Country",
            markers=True,
            title="Australia’s Tyre Trade Balances by Partner",
            labels={"Trade_balance": "Trade balance (A$ thousands)"}
        )

        fig.add_hline(y=0, line_dash="dash", line_color="grey")
        fig.show(renderer="vscode")


plot_button.on_click(update_chart)

In [44]:
plot_button.on_click(update_chart)

display(country_input, plot_button, chart_output)

Text(value='Canada', description='Countries:', layout=Layout(width='600px'), placeholder='Canada, Japan, New Z…

Button(description='Plot', style=ButtonStyle())

Output()

### Changes in Trade Balances Between 2006 and 2025

Compare each partner’s trade balance in 2006 and 2025 to identify the largest increases and decreases.

Change in trade balance = 2025 trade balance − 2006 trade balance.

A positive change indicates a larger surplus or smaller deficit, while a negative change indicates a smaller surplus or larger deficit. A partner may also switch between surplus and deficit.

Values are in A$ thousands. This comparison covers the 22 matched partners and measures the change between the two endpoints, rather than fluctuations throughout the period.

In [45]:
bal_comp = trade_matched[["Country","2006_TB","2025_TB"]].copy()
bal_comp["Change"]= bal_comp["2025_TB"] - bal_comp["2006_TB"] 
bal_comp.sort_values("Change", ascending=True).reset_index().drop(columns="index")

0                    Country  2006_TB  2025_TB  Change
0                      China  -250714 -1186722 -936008
1                      Japan  -444947  -986340 -541393
2              United States  -200097  -612046 -411949
3                   Thailand   -84777  -484188 -399411
4                      Spain   -47220  -155378 -108158
5                      India   -17344   -91363  -74019
6                  Indonesia   -15302   -63644  -48342
7                   Malaysia   -27185   -39922  -12737
8                   Portugal    -1521   -12128  -10607
9                Netherlands    -1561    -9404   -7843
10                     Italy   -20926   -27841   -6915
11                    France   -30467   -34964   -4497
12               Philippines   -11946   -14938   -2992
13              South Africa    -5870    -7359   -1489
14                    Canada    -2447    -2076     371
15  Hong Kong (SAR of China)    -1607     -253    1354
16      United Arab Emirates     -450     1913    2363
17                 Singapore    -6135    -3420    2715
18                   Germany   -40389   -35805    4584
19            United Kingdom   -27870    -8698   19172
20         Republic of Korea  -129838   -97293   32545
21               New Zealand   -26390    21065   47455

#### Observations: Changes Between 2006 and 2025

China recorded the largest widening of its tyre-trade deficit, increasing by AUD 936.008 million. Japan and the United States recorded the next-largest increases in deficits.

Canada, Singapore, Hong Kong, Germany, the United Kingdom and the Republic of Korea recorded smaller deficits in 2025 than in 2006, but remained in deficit.

Both New Zealand and the United Arab Emirates moved from deficits in 2006 to surpluses in 2025. New Zealand recorded the largest positive change in trade balance, at AUD 47.455 million.

Overall, 14 of the 22 matched partners had more negative trade balances, while eight had more positive balances.

This comparison measures changes between two endpoints. It does not describe fluctuations during the intervening years or explain their causes.

## Conclusion: Australia’s Tyre Trade Balances, 2006–2025

Of the 167 export partners assessed, 38 had complete data for all 20 years, while 129 were excluded. Of the 134 import partners assessed, 41 had complete data and 93 were excluded. Matching the two complete-data tables produced 22 partners with both import and export data throughout 2006–2025.

Australia recorded at least one year of tyre-trade deficit with every matched partner. Deficits persisted across all 20 years for 16 partners. Australia recorded at least one surplus year with six partners: New Zealand, Hong Kong, South Africa, the United Arab Emirates, Singapore and the Netherlands. New Zealand had the most surplus years, with 19 surpluses and one deficit. No partner recorded an exactly balanced trade position in any year.

In 2025, Australia recorded deficits with 20 of the 22 partners. Only New Zealand and the United Arab Emirates recorded surpluses, at AUD 21.065 million and AUD 1.913 million respectively. China had the largest deficit, at approximately AUD 1.187 billion, followed by Japan and the United States.

The time-series chart shows that balances fluctuated, while deficits with China, Japan and the United States widened overall. Between 2006 and 2025, China recorded the largest widening of its deficit, at AUD 936.008 million, followed by Japan at AUD 541.393 million and the United States at AUD 411.949 million.

Canada, Singapore, Hong Kong, Germany, the United Kingdom and the Republic of Korea had smaller deficits in 2025 than in 2006. New Zealand and the United Arab Emirates moved from deficits in 2006 to surpluses in 2025. Overall, 14 partners had more negative balances and eight had more positive balances between the two endpoints.

These findings describe the 22 partners selected for complete data, not all Australian tyre trade. The analysis identifies patterns and changes but does not establish their causes. Monetary changes are not adjusted for inflation.